### ISSUE TITLE
使用后 webview 文字跟图片都有点锯齿

### ISSUE THREAD

**Issue by dyzyang** [genius158/FlutterTest#2]
如题

**Comment by genius158** [comment]
涉及纹理的，目前还没看到太好的方法，比较可行的就是动态更改RenderView的configuration，也就是说界面中包涵来自native的控件，那么该界面都需要采用原本的屏幕参数

**Comment by phoenixsky** [comment]
webview锯齿的还是很明显的.我没试出来.
这里针对webview要怎么动态更改.可否出个demo?
